name: Build TA-Lib wheels for Linux

on:
  workflow_dispatch:

env:
  TALIB_C_VER: 0.6.2
  TALIB_PY_VER: 0.6.0
  PIP_NO_VERIFY: 0
  PIP_VERBOSE: 1
  CIBW_BUILD_VERBOSITY: 2
  CIBW_BEFORE_BUILD: pip install -U setuptools wheel numpy Cython
  CIBW_TEST_REQUIRES: pytest pandas polars
  CIBW_TEST_COMMAND: >
    cd .. &&
    pytest --rootdir=/ -k "not RSI and not threading" {project}/tests
  CIBW_TEST_SKIP: "*win32 cp37* cp38* cp39*"
  CIBW_SKIP: "pp* cp36*"

jobs:
  build_amd64:
    name: Build AMD64 wheels
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      - run: chmod +x && build.sh
        shell: bash
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ENVIRONMENT_LINUX: >
            TA_LIBRARY_PATH="ta-lib-$TALIB_C_VER/_build;$LIB"
            TA_INCLUDE_PATH="ta-lib-$TALIB_C_VER/include;$INCLUDE"
            PIP_NO_BUILD_ISOLATION=false
